[package]
name = "engine-js"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
boa_engine = "0.19"
boa_gc = "0.19"
boa_parser = "0.19"
engine-dom = { path = "../dom" }
engine-css = { path = "../css" }
